### ISSUE TITLE
Style 😎: Linters etc

### ISSUE THREAD

**Issue by waffle2k** [tommertron/CovidReport#9]
https://books.agiliq.com/projects/essential-python-tools/en/latest/linters.html has a good list of style linters to ensure code consistency (and to a lesser degree, quality).  Having consistently formatted code makes reviewing a much lower cognitive load, as the style of the code will look the same regardless of the author of the PR.

[PEP8](https://books.agiliq.com/projects/essential-python-tools/en/latest/linters.html#pep8) is the official python style, and there are linters that enforce it like [flake](https://books.agiliq.com/projects/essential-python-tools/en/latest/linters.html#flake8).

There are auto-formatters like [black](https://books.agiliq.com/projects/essential-python-tools/en/latest/linters.html#black), which are a little heavy handed, but generally produce really nicely formatted code that is PEP8 compliant, and which also tends to format the code in a way that makes side-by-side code review a little nicer (I'm actually really used to black since we use it at work, but it's not everyone's cup of tea)

Thoughts on selecting & enforcing a linter to the project?

**Comment by tommertron** [comment]
All for it!

**Comment by waffle2k** [comment]
Ok amazing. I'll put up a PR today, and will see if I can setup a GitHub
action to comment on offending lints etc

**Comment by waffle2k** [comment]
A'ight, the lint hooks are running in https://github.com/tommertron/CovidReport/pull/10 but they're VERY loud and noisy until the existing codebase is combed free of lint nits.

@tommertron, ping me once all of your WIP changes land, and then we can just do a giant lint PR to avoid rebase hell.

**Comment by tommertron** [comment]
Not a huge fan of double quotation marks, but makes sense to use the standard. Would you consider this issue closed now, or is there more to be done?

**Comment by waffle2k** [comment]
Yeah, I think that it can be closed since the goal of this issue wasn't fixing all of the lint issues, but rather settling on a linter & formatter, and integrating it with gh actions (which have all been done).

I'm going to close this out, and consider the remaining errors as tech debt that we'll burn down through iterations.
